# Generated by Django 4.1 on 2023-06-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('taxtype', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
