# Generated by Django 4.1 on 2023-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0002_tax_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
