# Generated by Django 4.1 on 2023-07-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0003_alter_taxratedetails_header_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='tax_authority_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapp.tax', verbose_name='Tax Authority Ref ID'),
        ),
    ]
