# Generated by Django 4.1 on 2023-06-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0003_tax_status_tax_ward_tax_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tax',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
